version: '3.8'

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./content:/app/content
    networks:
      - mynetwork
    depends_on:
      - ffmpeg

  ffmpeg:
    build: 
      context: .
      dockerfile: Docker_ffmpeg
    #image: jrottenberg/ffmpeg:latest
   # command: ["bash", "-c", "tail -f /dev/null"]
    #command: ["tail", "-f", "/dev/null"]
    volumes:
      - ./content:/app/content
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
